// <auto-generated />
using System;
using DAL.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(UczelniaDBContext))]
    [Migration("20240419145003_migracja 1")]
    partial class migracja1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Grupa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grypy");
                });

            modelBuilder.Entity("Models.Historia", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdGrupy")
                        .HasColumnType("int");

                    b.Property<int?>("IdStudenta")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TypAkcji")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupy");

                    b.ToTable("Historie");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdGrupy")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdGrupy");

                    b.ToTable("Studentci");
                });

            modelBuilder.Entity("Models.Historia", b =>
                {
                    b.HasOne("Models.Grupa", "Grupa")
                        .WithMany()
                        .HasForeignKey("IdGrupy");

                    b.Navigation("Grupa");
                });

            modelBuilder.Entity("Models.Student", b =>
                {
                    b.HasOne("Models.Grupa", "Grupa")
                        .WithMany("Studenci")
                        .HasForeignKey("IdGrupy");

                    b.Navigation("Grupa");
                });

            modelBuilder.Entity("Models.Grupa", b =>
                {
                    b.Navigation("Studenci");
                });
#pragma warning restore 612, 618
        }
    }
}
